// the let section is to declare/identify the section box in scrollytelling map
// put the top title below
// you can choose the style (h1 for heading 1, h2, etc and p for paragraph)
let topTitleDiv = "<h4>glocur</h4>";

// put the title below
let titleDiv =
  "<h1>Global Crisis and Urban Regeneration</h1>";

// put the byline
let bylineDiv = "<p class='byline'>by Group 13 - Asian Geeks<br>(Juerong Wang, Rahmadita Listianingrum, Yiru Li)</p>";

// put the description here (can embed video and pictures)
let descriptionDiv =
  '<iframe width="720" height="480" src="https://www.youtube.com/embed/zkxl8na9gE8" title="The 2008 Financial Crisis: Explaining the Start" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>' +
  "<p style=margin-top:50px>Introduction</p>" +
  "<p style=“text-align:center;margin-left: 50px; margin-right: 50px;”>The crisis has been described as a series of shocks to the global economy that began with the bursting of the US and UK housing bubbles in 2007, spread across Europe in 2008 and 2009 as a financial crisis, and culminated in full-blown sovereign debt crisis. Rather than a single event, the crisis can be seen as a series of events generated by systemic economic and social imbalances, which manifested globally at different points in time. There are several ways to determine a situation, which affects how the city responds. Although the main discussion of the crisis has been economic (i.e. unemployment, recession), the crisis has also had social, environmental and institutional impacts on cities.</p>" +
  '<p style="text-align:center;margin-top:100px">Lets scroll!<br>▼</p>';

// put the footer information here
let footerDiv =
  '<p> </p>';
//'<p>This base map is based on data by the <a href="https://sipsn.menlhk.go.id/sipsn/">Indonesian Ministry of Environment and Forestry</a> and <a href="https://data.jakarta.go.id">Open Data Jakarta</a>. </br>This project can be found in this <a href="https://github.com/ListianingrumR/digiviz-individual.git">Github repository</a>.</p>' +
//'<p><a href="https://www.mapbox.com/about/maps/" target="_blank">© Mapbox</a> | <a href="https://www.datawrapper.de" target="_blank">© Datawrapper</a> | <a href="https://www.ucl.ac.uk/bartlett/casa/bartlett-centre-advanced-spatial-analysis">UCL Centre for Advanced Spatial Analysis</a></p>';

// put the 1st box navigation here
let divChapter1 =
  "<p><b>Global Crisis - The History</b></p>" + "<hr>" +
  "<p><img src='img/timeline.png'></p>" + "<hr>";
// https://www.kent.ac.uk/business-and-partnerships/news-and-events/922/the-impact-of-cost-cutting-actions-on-employee-relations-and-workplace-grievances-what-weve-learned-from-the-great-recession
//"<p><b>The Great Recession</b></p>" +
//"<p>The Great Recession brief explanation</p>"

let divChapter2 =
  "<p style=margin-top:50px><b>World GDP Growth(%) from 2006-2016</b></p>" +
  '<iframe width="100%" height="650px" src= "map/world_gdp_2.html" frameBorder="0"</iframe>';

// continue to next box/chapter
let divChapter3 =
  "<p><b>Global Unemployment Rate(%) from 2006-2016</b></p>" + "<hr>" +
  '<iframe width="100%" height="650px" src= "map/world_unemployment_rate.html" frameBorder="0"</iframe>' + "<hr>";
// https://www.thebalancemoney.com/lehman-brothers-collapse-causes-impact-4842338


let divChapter4 =
  '<div id="chart-container"></div>' +
  '<iframe src="chart/timeline.html" width="100%" height="500px" frameBorder="0"></iframe>';
//"<p><img src='images/jakarta-waste-volume-per-day-by-type-ton.png'></p>"+
//"<p class='data-source'>Data source: <a href='https://datawrapper.dwcdn.net/m2o0s/3/'>Environment Office DKI Jakarta</a></p>"+
//"<p>Jakarta is divided into 6 districts, which are Thousand Islands, Central Jakarta, North Jakarta, West Jakarta, East Jakarta and South Jakarta.</p>"+
//"<p><img src='images/jakarta-waste-generation-by-district-per-day-ton.png'></p>"+
//"<p class='data-source'>Data source: <a href='https://datawrapper.dwcdn.net/o50nX/1/'>Indonesian Ministry of Environment and Forestry</a></p>";
//https://datawrapper.dwcdn.net/o50nX/1/

let divChapter5 =
  "<p><b>USA Housing bubble</b></p>" + "<hr>" +
  '<iframe src="chart/homevacant.html" width="100%" height="500px" frameBorder="0"></iframe>';
//"<p>Bridging to the USA (housing bubble, subprime mortgage)</p>";
// Housing Interactive Map
//'<div class="chart-container" data-aos="fade-up"></div>' +
//'<iframe id="housing" src="../housing/housing-foreclosure.html" height="800px" width="100%" frameBorder="0"></iframe>';

let divChapter6 =
  "<p><b>The United States housing crisis led to foreclosure </b></p>" + "<hr>" +
  "<p>The map shows the </p>" +
  "<p>Legend </p>";
  

let divChapter7 =
  "<p><b>Top 10 States with the highest number of housing foreclosure</b></p>" + "<hr>" +
  '<iframe title="US Housing Foreclosure 2009" aria-label="Grouped Bars" id="datawrapper-chart-dFsXm" src="https://datawrapper.dwcdn.net/dFsXm/3/" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="431" data-external="1"></iframe><script type="text/javascript">!function(){"use strict";window.addEventListener("message",(function(a){if(void 0!==a.data["datawrapper-height"]){var e=document.querySelectorAll("iframe");for(var t in a.data["datawrapper-height"])for(var r=0;r<e.length;r++)if(e[r].contentWindow===a.source){var i=a.data["datawrapper-height"][t]+"px";e[r].style.height=i}}}))}();</script>'+
  "<p>California, more than any other state, was the source of widespread mortgage lending, skyrocketing housing prices, and fraudulent subprime businesses.  Behind that was California's pioneering position in urban, industrial, and fiscal developments in the United States, which fueled the demands and strains on the financial system. (Bardhan and Walker, 2010)</p>";

let divChapter8 =
  "<p><b>The United States situation after the stock market crash</b></p>" + "<hr>" +
  '<iframe src="map/usa.html" width="100%" height="650px" frameBorder="0"></iframe>';

let divChapter9 =
  "<p><b>Michigan was hit hard</b></p>" + "<hr>" +
  "<p>Amidst the loss of nearly one million automotive industry related jobs, Michigan experienced the highest unemployment rate in the nation during the recession, peaking at 15.3%. This further exacerbated the state's housing crisis and weakened the labor market.</p>";
//"<p><b>California hit hard</b></p>" + "<hr>" +
//"<p>Here is the changing of Urbanised Area in Los Angeles, California 10 years after the crisis (2008 vs 2018). We can see there are some of urbanised area that are shrinked in the past decade.</p>" + "</hr>" +
//'<iframe src="map/urban.html" width="100%" height="650px" frameBorder="0"></iframe>';

// YR codes
// Impact of the Global Financial Crisis on Australia
//share price
let divChapter10 =
  "<p><b>Australia</b></p>" + "<hr>" +
  "<p>The global financial crisis had a profound impact on countries and regions worldwide, including Australia, even though they were geographically distant. In Australia, the crisis led to a significant decline in stock market capitalization, with a loss of over A$771 billion, equivalent to 65% of the country's GDP in 2008. The household sector also experienced a sharp decline in net worth. As approximately 43% of adults in Australia own shares directly or indirectly, the drop in net worth was primarily caused by the decrease in the value of share portfolios due to stock market declines. Even by 2009, the ASX price index remained 30% below its peak in November 2007. The Australian economy has been perceived as having uneven growth, and a \"two-speed\" economy exists, partly due to natural disasters such as the 2010-2011 Queensland floods and the impact of a high Australian dollar.</p>" +
  '<iframe src="chart/share_price.html" width="100%" height="450px" style="border: 0"></iframe>';

// unemployment rate
let divChapter11 =
  '<p>However, despite these challenges, Australia performed relatively well compared to the United Kingdom and the United States during the crisis. The employment situation in Australia remained favorable, as shown in the graph below. While the average OECD unemployment rate increased from 5.7% to 8.8% during the crisis and then decreased to 8.2% by Q2 2011, Australia\'s unemployment rate increased from 4.2% to a peak of 5.7% during the crisis and then fell to 4.9% by Q2 2011. Australia also had a lower long-term unemployment rate than the OECD average in 2011. This can be attributed to the fact that many employers opted to reduce working hours rather than laying off workers, resulting in an average reduction of around 3.5% in working hours. This approach was similar to that of Germany, where the labor market demonstrated greater resilience compared to other OECD countries.</p>' +
  '<iframe src="chart/unem_many.html" width="100%" height="450px" style="border: 0"></iframe>';

// reasons on states
let divChapter12 =
  "<p>So, why did Australia perform well during the crisis? There are several key reasons\:</p>" +
  '<h4>1. Robust banking sector:</h4>' +
  "<p>Australia's banking sector was in a relatively strong position at the start of the crisis, characterized by sound lending standards, adequate capital levels, and profitable operations. This enabled Australian banks to navigate the crisis more effectively than their counterparts in many other countries.</p>" +
  '<h4>2. Effective policy response:</h4>' +
  "<p>The Australian government and the Reserve Bank of Australia(RBA) responded swiftly and decisively to the crisis.The RBA implemented significant interest rate cuts, and the government implemented a substantial fiscal stimulus package.These measures helped to stimulate demand in the economy during a time of severe stress. <br> <br>The share price analysis also indicates that Australian share prices continuously outperformed those of over 19 European countries during the market crash and subsequent recovery.</p>" +
  '<h4>3. Strong trade links with China:</h4>' +
  "<p>Australia benefited from its strong trade ties with China, which continued to experience rapid growth during the crisis.Demand from China for Australian commodities, particularly iron ore and coal, remained robust, providing crucial support to the Australian economy.</p >" +
  '<h4>4. Commodity boom:</h4>' + '<p>Australia\'s economy heavily relies on the mining sector, and the commodity boom that preceded the 2008 crisis helped cushion the Australian economy against the downturn. High commodity prices supported income and employment in the mining sector, which subsequently flowed through to the rest of the economy.</p>' +
  '<h3>Choropleth map</h3>' + '<p> The choropleth map on the left presents the personal bankruptcy rate across Australian states in the fiscal year 2007-2008. Darker shades signify higher rates, indicating a spatial pattern of financial distress. Notably, mining-focused states like Western Australia had lower bankruptcy rates, suggesting their economic resilience during the concurrent global financial crisis.</p>'

// reasons on cities
let divChapter13 =
  '<p>In addition, at the city level, it can be inferred that cities in mining-rich states such as Perth (Western Australia) and Brisbane (Queensland) fared relatively well in October 2009, which had the highest unemployment rate, due to the aforementioned reasons.</p>' +

  '<iframe src="chart/city_unem_chart.html" width="100%" height="450px" style="border: 0"></iframe>'; +
    '<p>In summary, Australia\'s ability to weather the global financial crisis can serve as an inspiration and guide for future policymakers. By maintaining a resilient banking sector, implementing effective policies, fostering strong international trade relations, and diversifying the economy beyond commodities, Australia can strive to mitigate the impact of future crises and sustain stable economic growth.</p>'

//YR

// the var section is to navigate the map in each chapter/box
var config = {
  style: "mapbox://styles/listianingrumr/clh73da2a00t201qyb97adh5y", // mapbox styles
  accessToken: "pk.eyJ1IjoibGlzdGlhbmluZ3J1bXIiLCJhIjoiY2xkYWhqNDZhMDFpajN2b2JlbWk0b3I5byJ9.MMQjrAuB1KMHcaKfXrnn3w", // mapbox token
  showMarkers: false, // no marker
  markerColor: "#327CA7", // marker color
  theme: "light",
  use3dTerrain: false, // if using 3d terrain
  topTitle: topTitleDiv,
  title: titleDiv,
  subtitle: "",
  byline: bylineDiv,
  description: descriptionDiv,
  footer: footerDiv,
  chapters: [ // chapter for basemap (in this example, it is from the introduction to chapter 1 using basemap)
    {
      id: "baseMap",
      alignment: "center",
      image: "",
      hidden: false,
      chapterDiv: divChapter1,
      location: { // identify the location, the zoom scale, the pitch and bearing
        center: [186.328125, 39.095963], // use bbox finder
        zoom: 1.5,
        zoomSmall: 1,
        pitch: 0,
        bearing: 0,
      },
      mapAnimation: "flyTo", // animation flyto
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [
        {
          layer: "usa",
          opacity: 0,
          duration: 0,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 0,
        },
        {
          layer: "michigan",
          opacity: 0,
          duration: 0,
        },
        {
          layer: "top10",
          opacity: 0,
          duration: 0,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 0,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 0,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 0,
          duration: 0,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 0,
        },
      ],
      onChapterExit: [
        {
          layer: "usa",
          opacity: 0,
          duration: 0,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 0,
        },
        {
          layer: "michigan",
          opacity: 0,
          duration: 0,
        },
        {
          layer: "top10",
          opacity: 0,
          duration: 0,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 0,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 0,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 0,
          duration: 0,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 0,
        },
      ],
    },
    {
      id: "globalcrisis",
      alignment: "center2",
      hidden: false,
      chapterDiv: divChapter2,
      location: {
        center: [186.328125, 39.095963],
        zoom: 1.5,
        zoomSmall: 1,
        pitch: 0,
        bearing: 0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [
        {
          layer: "usa",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "michigan",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "top10",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
      ],
      onChapterExit: [
        {
          layer: "usa",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "michigan",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "top10",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
      ],
    },
    {
      id: "globalhpi",
      alignment: "center2",
      hidden: false,
      chapterDiv: divChapter3,
      location: {
        center: [186.328125, 39.095963],
        zoom: 1.5,
        zoomSmall: 2,
        pitch: 0,
        bearing: 0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [
        {
          layer: "usa",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "michigan",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "top10",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
      ],
      onChapterExit: [
        {
          layer: "usa",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "michigan",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "top10",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
      ],
    },
    {
      id: "usa",
      alignment: "center",
      hidden: false,
      chapterDiv: divChapter4,
      location: {
        center: [260.683594, 39.571822],
        zoom: 4,
        zoomSmall: 2,
        pitch: 0,
        bearing: 0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [
        {
          layer: "usa",
          opacity: 1,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "michigan",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "top10",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
      ],
      onChapterExit: [
        {
          layer: "usa",
          opacity: 1,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "michigan",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "top10",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
      ],
    },
    {
      id: "usa2",
      alignment: "center",
      hidden: false,
      chapterDiv: divChapter5,
      location: {
        center: [260.683594, 39.571822],
        zoom: 4,
        zoomSmall: 2,
        pitch: 0,
        bearing: 0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [
        {
          layer: "usa",
          opacity: 1,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "michigan",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "top10",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
      ],
      onChapterExit: [
        {
          layer: "usa",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "michigan",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "top10",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
      ],
    },
    {
      id: "usa3",
      alignment: "left",
      hidden: false,
      chapterDiv: divChapter6,
      location: {
        center: [260.683594, 39.571822],
        zoom: 4,
        zoomSmall: 2,
        pitch: 0,
        bearing: 0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [
        {
          layer: "usa",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 1,
          duration: 300,
        },
        {
          layer: "michigan",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "top10",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
      ],
      onChapterExit: [
        {
          layer: "usa",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "michigan",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "top10",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
      ],
    },
    {
      id: "usa4",
      alignment: "left",
      hidden: false,
      chapterDiv: divChapter7,
      location: {
        center: [240.683594, 39.571822],
        zoom: 3.7,
        zoomSmall: 2,
        pitch: 0,
        bearing: 0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [
        {
          layer: "usa",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "michigan",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "top10",
          opacity: 1,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
      ],
      onChapterExit: [
        {
          layer: "usa",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "michigan",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "top10",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
      ],
    },
    {
      id: "california",
      alignment: "center2",
      hidden: false,
      chapterDiv: divChapter8,
      location: {
        center: [260.683594, 39.571822],
        zoom: 4,
        zoomSmall: 2,
        pitch: 0,
        bearing: 0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [
        {
          layer: "usa",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "michigan",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "top10",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
      ],
      onChapterExit: [
        {
          layer: "usa",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "michigan",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "top10",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
      ],
    },
    {
      id: "california2",
      alignment: "right",
      hidden: false,
      chapterDiv: divChapter9,
      location: {
        center: [-80.718559, 41.158401],
        zoom: 5.5,
        zoomSmall: 2,
        pitch: 50,
        bearing: 30,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [
        {
          layer: "usa",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "michigan",
          opacity: 1,
          duration: 300,
        },
        {
          layer: "top10",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
      ],
      onChapterExit: [
        {
          layer: "usa",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "michigan",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "top10",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
      ],
    },
    //YR
    {
      id: "Australia",
      alignment: "center",
      hidden: false,
      chapterDiv: divChapter10,
      location: {
        center: [151.2, -33.85],
        zoom: 3.5,
        zoomSmall: 3,
        pitch: 0,
        bearing: 0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [
        {
          layer: "usa",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 1,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
      ],
      onChapterExit: [
        {
          layer: "usa",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 1,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
      ],
    },
    {
      id: "Australia2",
      alignment: "center",
      hidden: false,
      chapterDiv: divChapter11,
      location: {
        center: [151.2, -33.85],
        zoom: 3.5,
        zoomSmall: 3,
        pitch: 0,
        bearing: 0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [
        {
          layer: "usa",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 1,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
      ],
      onChapterExit: [
        {
          layer: "usa",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
      ],
    },
    {
      id: "Australia3",
      alignment: "right",
      hidden: false,
      chapterDiv: divChapter12,
      location: {
        center: [155.2093, -28.8688],
        zoom: 3.5,
        zoomSmall: 3,
        pitch: 0,
        bearing: 0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [
        {
          layer: "usa",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 1,
          duration: 300,
        },
      ],
      onChapterExit: [
        {
          layer: "usa",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
      ],
    },
    {
      id: "Australia4",
      alignment: "right",
      hidden: false,
      chapterDiv: divChapter13,
      location: {
        center: [155.2093, -28.8688],
        zoom: 3.5,
        zoomSmall: 3,
        pitch: 0,
        bearing: 0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [
        {
          layer: "usa",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 1,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 1,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 1,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
      ],
      onChapterExit: [
        {
          layer: "usa",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "housing-filed08",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "major-cities-name",
          opacity: 1,
          duration: 300,
        },
        {
          layer: "major-cities-dypf5x",
          opacity: 1,
          duration: 300,
        },
        {
          layer: "gadm41-aus-1-349tki",
          opacity: 0,
          duration: 300,
        },
        {
          layer: "state-bkrp-0708-cr0wbs",
          opacity: 0,
          duration: 300,
        },
        {
          // Callback function to remove popups
          callback: () => {
            if (window.cityPopups) {
              window.cityPopups.forEach(popup => popup.remove());
            }
          }
        },
      ],
    },
    //YR
    /*
         {
           layer: "tps",
           opacity: 0,
           duration: 300,
         },
         {
           layer: "saringan-sampah-sungai",
           opacity: 0,
           duration: 300,
         },
         {
           layer: "timbulandki22",
           opacity: 0,
           duration: 300,
         },
         {
           layer: "seribu",
           opacity: 1,
           duration: 300,
         },
         {
           layer: "jakpus",
           opacity: 0,
           duration: 300,
         },
         {
           layer: "jakut",
           opacity: 0,
           duration: 300,
         },
         {
           layer: "jakbar",
           opacity: 0,
           duration: 300,
         },
         {
           layer: "jaktim",
           opacity: 0,
           duration: 300,
         },
         {
           layer: "jaksel",
           opacity: 0,
           duration: 300,
         },
       ],
       onChapterExit: [
         {
           layer: "seribu",
           opacity: 0,
           duration: 300,
         },
       ],
     },*/
  ],
};